### ISSUE TITLE
Clarifying if/else logic in handlers.js

### ISSUE THREAD

**Issue by rachaelcodes** [FAC-11/week-4-TAAA#45]
Could the code be clarified into a single if/if-else/.../else structure?

**Comment by finnhodgkin** [comment]
The line-breaks between if and else blocks are not really common practice either. It makes it hard to tell how statements lead into one another:

https://github.com/FAC-11/week-4-TAAA/blob/master/src/handlers.js#L22-L26

I usually go with this structure:

```js
if (condition) {
    // blah
} else if (condition) {
    // content
} else {
    // more content
}
```

Because it allows you to remove or comment out conditions by just grabbing a single line of the `if` statement plus the content (nice git diffs):

```js
if (condition) {
    // blah
} else {
    // more content
}
```
